const products ={
  state: {
    products: [
      {
        id: 1,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "30",
        image: require("@/assets/images/products/product-1.jpg"),
        discount: "",
        link: "/product-1",
      },
      {
        id: 2,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-2.jpg"),
        discount: "20%",
        link: "/product-2",
      },
      {
        id: 3,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "40",
        image: require("@/assets/images/products/product-3.jpg"),
        discount: "",
        link: "/product-3",
      },
      {
        id: 4,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "40",
        image: require("@/assets/images/products/product-4.jpg"),
        discount: "",
        link: "/product-4",
      },
      {
        id: 5,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "60",
        image: require("@/assets/images/products/product-5.jpg"),
        discount: "",
        link: "/product-5",
      },
      {
        id: 6,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "30",
        image: require("@/assets/images/products/product-6.jpg"),
        discount: "",
        link: "/product-6",
      },
      {
        id: 7,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-7.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 8,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 9,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 10,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 11,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 12,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 13,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 14,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 15,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      },
      {
        id: 16,
        category: "MEN'S CLOTHES",
        title: "Quis Nostrud Exercitation",
        price: "25",
        image: require("@/assets/images/products/product-8.jpg"),
        discount: "20%",
        link: "/product-7",
      }
     ],
  },
  getters: {
    products: function(state) {
      return state.products;
    }
  }
}
export default products;